# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and integrates the results with GitHub Advanced Security
# code scanning feature.  For more information on the Anchore scan action usage
# and parameters, see https://github.com/anchore/scan-action. For more
# information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype
name: Anchore Container Scan

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '27 2 * * 6'

jobs:
  Anchore-Build-Scan:
    runs-on: ubuntu-latest
    steps:
    - name: Run the Anchore scan action itself with GitHub Advanced Security code scanning integration enabled
      id: scan
      uses: anchore/scan-action@v3
      with:
        image: "ilteoood/local_m3u8:latest"
        output-format: sarif
        fail-build: false
    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
    - name: Run Anchore scan for JSON output
      id: scan-json
      uses: anchore/scan-action@v3
      with:
        image: "ilteoood/local_m3u8:latest"
        output-format: json
        fail-build: false
    - name: Upload Anchore JSON Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: anchore-scan-results
        path: ${{ steps.scan-json.outputs.json }}
