name: Build only image
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Get dependencies
        run: go get all
      - name: Run tests
        run: go test -v ./...
      - name: Build image
        uses: ilteoood/docker_buildx@master
        with:
          tag: latest,2.0.0
          platform: linux/amd64,linux/arm64,linux/arm/v7
          imageName: ilteoood/local_m3u8