name: Build and publish image
on:
  release:
    types: [published]
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          tag: latest,1.0.0
          imageName: ilteoood/local_m3u8
          platform: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          publish: true
          dockerHubUser: ilteoood
          dockerHubPassword: ${{ secrets.DOCKER_HUB_PASSWORD }}